CREATE TABLE IF NOT EXISTS user (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  username VARCHAR(255),
  password VARCHAR(255),
  enabled TINYINT(1) DEFAULT 0,
  email VARCHAR(255),
  phone BIGINT(20)
);

CREATE TABLE IF NOT EXISTS role (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  role VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS user_role (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INTEGER NOT NULL,
  role_id INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,
  FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE CASCADE
);
